### ISSUE TITLE
Add Optional<T>#Bind()

### ISSUE THREAD

**Issue by Foxtrek64** [Remora/Remora.Rest#30]
**Description**
`Bind()` or `FlatMap()` functions very similarly to the existing Map() function but works for situations where the callback returns `Optional<T>` rather than `T`.

**Why This is Needed**

If you use a function that returns `Optional<T>` in `Map` the result ends up as `Optional<Optional<T>>`

**Alternatives Considered**

The mapping function callback can attempt to convert its `Optional<T>` into `T` but this may not always be appropriate.

Alternatively, consumer can use `Map()` and just know they have to unwrap two optionals before getting to their desired value.

**Additional Details**

I think the implementation should allow for us to chain these two methods internally, if desired. That said, a couple conditions in an if check isn't very expensive so we could make them two separate functions.

`Bind` and `FlatMap` are the most common names for these types, but some discussion is welcome on naming them.

**Example Usage**
```cs
Option<int> ParseInt(string s) => int.TryParse(s, out int i) ? i : default;

// Current
int age = person.Age
    .Map(ParseInt) // Optional<Optional<int>>
    .Value // Outer optional always has value. Returns Optional<int>
    .OrThrow(new Exception("Person did not provide an age."));

// New
int age = person.Age
    .Bind(ParseInt)
    .OrThrow(new Exception("Person did not provide an age."));
```

Proposed Implementation
```cs
public Optional<TResult> Bind<TResult>(Func<TValue, Optional<TResult>> mappingFunc)
{
    return this.HasValue
        ? mappingFunc(_value)
        : default(Optional<TResult>);
}
```
The difference here is that `mappingFunc` from Map() returns `TResult`, which triggers the implicit operation converting `TResult` to `Optional<TResult>`. Because `mappingFunc` from `Bind()` returns `Optional<TResult>`, no operator is triggered and it returns the direct result from the mapping function.

**Comment by Nihlus** [comment]
I like this suggestion. FlatMap seems to be the more appropriate name for the function - some brief reading suggests that "Bind" is more geared towards lists of elements, and to me it sounds more akin to linking two optionals together in some fashion. It's also more symmetrical with the current Map API.

**Comment by VelvetToroyashi** [comment]
I think flatmap is a better name as well, Rust's closest equivalent appears to be `Optional<T>.and()`, (though this issue propposes what's effectively `and_then`; in either case, I'd personally like to see both implemented in this regard)
